### ISSUE TITLE
Accesos a API

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/waze-api#11]
The waze guy has asked me to draw polygons for where we want Waze API access with this tool
http://arthur-e.github.io/Wicket/sandbox-gmaps3.html
"please use this tool to draw polygons around the city of Madrid, San Diego, and Bristol. Then, send the multi-polygon outputs back to me and we can extend your temporary API access."
Please can you do it for Madrid and then I'll get the same from San Diego and Bristol UK (interested cities)?

Cuando lo tengas te pones en contacto directamente con Flo: flo@carto.com

**Comment by cayetanobv** [comment]
Ya están desplegados conectores de San Diego y Madrid, y se están ya subiendo datos a Carto (scheduler cada 2 minutos). Falta Bristol, que no tengo datos de API aún. Si puedes preguntar @paulajpozuelo a ver si lo tienen y no lo han mandado.
